### PR TITLE
Implement generic instance handler interface

### PR DESCRIPTION
**Pull request by copygirl**
One interface that handles installing (creating) and updating, possibly removing instances for specific targets: Vanilla, Server, MultiMC, ...

I have an open question regarding this: Do we continue to use a hidden file in the `.git` folder to specify the type of an instance or try to guess the instance type by files (server .jar, client options, MultiMC instance.cfg)? The former, current approach feels like a hack to me and has the issue of what if an instance is installed automatically or moved (from Vanilla to MultiMC for example)?

### CODE REVIEW

**Comment by NikkyAI** [comment]
we can move the file into the instance folder if you want.. detecting the type of instance might lead into more problems than making people edit a value when moving the folder

**Comment by copygirl** [comment]
If it's going to be a general instance configuration that also includes which features were enabled by the user and such, I suppose it could work.

**Comment by copygirl** [comment]
Updated the interface. Could we work with this?

**Comment by copygirl** [comment]
Aaand.. we could work with this now, I think.

Still some work that we could do, open questions, `TODO`s and `FIXME`s and all.

**Comment by NikkyAI** [comment]
maybe change the filename to something shorter, hidden by default like 
`.alpacka.instance.json`
and if its supposed to be looked at and edited by the user.. use yaml ?

**Comment by copygirl** [comment]
The packbuild is also not really meant to be edited by the user, right? I don't think we should hide it by default. Shorter name I can agree with. Perhaps I should reevaluate whether these files should go into an `alpacka` folder or not.

**Comment by copygirl** [comment]
Added a `UserConfig` sort of helper base class now, using it for MultiMC and Curse auth. Currently not doing any sanity checking or asking the user to input anything if it doesn't exist.

**Pull request merged**
